$ANSIBLE_VAULT;1.1;AES256
63376263643132396164666262393238613565383238656237306563306538326339663766613534
3262633331393931376666353135353336626563663938360a623337343335343739326232633431
38663961313062363134366661633334336338386432336431343337333438393138663034313836
6135663164366239320a663631663263376337336262363438393333623466393861346636343935
66623866366131616363353065656563613362383966386437303465343131313730356530343733
35313639343030396361393966613737646163626265363538313865356666633533643466626466
353563306135356236383166313866633139
