apiVersion: v1
kind: Service
metadata:
  name: diabetes-api-service
  namespace: diabetes-prediction
spec:
  selector:
    app: diabetes
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP