apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diabetes-prediction-ingress
  namespace: diabetes-prediction
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: diabetes.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: diabetes-api-service
                port:
                  number: 8000