apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diabetes-api-ingress
  namespace: diabetes-prediction
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /predict$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: diabetes.local
      http:
        paths:
          - path: /predict(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: diabetes-api-service
                port:
                  number: 8000
